// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.imlaidian.protobuf.model {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CDBStatus {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_imlaidian_protobuf_model_CDBStatusModel__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.CDBStatusModel, global::com.imlaidian.protobuf.model.CDBStatusModel.Builder> internal__static_com_imlaidian_protobuf_model_CDBStatusModel__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static CDBStatus() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9DREJTdGF0dXMucHJvdG8SHGNvbS5pbWxhaWRpYW4ucHJvdG9idWYubW9k", 
            "ZWwijAEKDkNEQlN0YXR1c01vZGVsEgwKAXYYASABKAlSAXYSEgoEdnRtcBgC", 
            "IAEoCVIEdnRtcBIOCgJ2cBgDIAEoCVICdnASEgoEdnVzZRgEIAEoCVIEdnVz", 
            "ZRIYCgd2c3RhdHVzGAUgASgJUgd2c3RhdHVzEhoKCHBvc2l0aW9uGAYgASgJ", 
            "Ughwb3NpdGlvbkIpChxjb20uaW1sYWlkaWFuLnByb3RvYnVmLm1vZGVsQglD", 
          "REJTdGF0dXNiBnByb3RvMw=="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_imlaidian_protobuf_model_CDBStatusModel__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_imlaidian_protobuf_model_CDBStatusModel__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.CDBStatusModel, global::com.imlaidian.protobuf.model.CDBStatusModel.Builder>(internal__static_com_imlaidian_protobuf_model_CDBStatusModel__Descriptor,
                new string[] { "V", "Vtmp", "Vp", "Vuse", "Vstatus", "Position", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CDBStatusModel : pb::GeneratedMessage<CDBStatusModel, CDBStatusModel.Builder> {
    private CDBStatusModel() { }
    private static readonly CDBStatusModel defaultInstance = new CDBStatusModel().MakeReadOnly();
    private static readonly string[] _cDBStatusModelFieldNames = new string[] { "position", "v", "vp", "vstatus", "vtmp", "vuse" };
    private static readonly uint[] _cDBStatusModelFieldTags = new uint[] { 50, 10, 26, 42, 18, 34 };
    public static CDBStatusModel DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override CDBStatusModel DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override CDBStatusModel ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.imlaidian.protobuf.model.CDBStatus.internal__static_com_imlaidian_protobuf_model_CDBStatusModel__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<CDBStatusModel, CDBStatusModel.Builder> InternalFieldAccessors {
      get { return global::com.imlaidian.protobuf.model.CDBStatus.internal__static_com_imlaidian_protobuf_model_CDBStatusModel__FieldAccessorTable; }
    }
    
    public const int VFieldNumber = 1;
    private bool hasV;
    private string v_ = "";
    public bool HasV {
      get { return hasV; }
    }
    public string V {
      get { return v_; }
    }
    
    public const int VtmpFieldNumber = 2;
    private bool hasVtmp;
    private string vtmp_ = "";
    public bool HasVtmp {
      get { return hasVtmp; }
    }
    public string Vtmp {
      get { return vtmp_; }
    }
    
    public const int VpFieldNumber = 3;
    private bool hasVp;
    private string vp_ = "";
    public bool HasVp {
      get { return hasVp; }
    }
    public string Vp {
      get { return vp_; }
    }
    
    public const int VuseFieldNumber = 4;
    private bool hasVuse;
    private string vuse_ = "";
    public bool HasVuse {
      get { return hasVuse; }
    }
    public string Vuse {
      get { return vuse_; }
    }
    
    public const int VstatusFieldNumber = 5;
    private bool hasVstatus;
    private string vstatus_ = "";
    public bool HasVstatus {
      get { return hasVstatus; }
    }
    public string Vstatus {
      get { return vstatus_; }
    }
    
    public const int PositionFieldNumber = 6;
    private bool hasPosition;
    private string position_ = "";
    public bool HasPosition {
      get { return hasPosition; }
    }
    public string Position {
      get { return position_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _cDBStatusModelFieldNames;
      if (hasV) {
        output.WriteString(1, field_names[1], V);
      }
      if (hasVtmp) {
        output.WriteString(2, field_names[4], Vtmp);
      }
      if (hasVp) {
        output.WriteString(3, field_names[2], Vp);
      }
      if (hasVuse) {
        output.WriteString(4, field_names[5], Vuse);
      }
      if (hasVstatus) {
        output.WriteString(5, field_names[3], Vstatus);
      }
      if (hasPosition) {
        output.WriteString(6, field_names[0], Position);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasV) {
        size += pb::CodedOutputStream.ComputeStringSize(1, V);
      }
      if (hasVtmp) {
        size += pb::CodedOutputStream.ComputeStringSize(2, Vtmp);
      }
      if (hasVp) {
        size += pb::CodedOutputStream.ComputeStringSize(3, Vp);
      }
      if (hasVuse) {
        size += pb::CodedOutputStream.ComputeStringSize(4, Vuse);
      }
      if (hasVstatus) {
        size += pb::CodedOutputStream.ComputeStringSize(5, Vstatus);
      }
      if (hasPosition) {
        size += pb::CodedOutputStream.ComputeStringSize(6, Position);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static CDBStatusModel ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static CDBStatusModel ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static CDBStatusModel ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static CDBStatusModel ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private CDBStatusModel MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(CDBStatusModel prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<CDBStatusModel, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(CDBStatusModel cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private CDBStatusModel result;
      
      private CDBStatusModel PrepareBuilder() {
        if (resultIsReadOnly) {
          CDBStatusModel original = result;
          result = new CDBStatusModel();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override CDBStatusModel MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.imlaidian.protobuf.model.CDBStatusModel.Descriptor; }
      }
      
      public override CDBStatusModel DefaultInstanceForType {
        get { return global::com.imlaidian.protobuf.model.CDBStatusModel.DefaultInstance; }
      }
      
      public override CDBStatusModel BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is CDBStatusModel) {
          return MergeFrom((CDBStatusModel) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(CDBStatusModel other) {
        if (other == global::com.imlaidian.protobuf.model.CDBStatusModel.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasV) {
          V = other.V;
        }
        if (other.HasVtmp) {
          Vtmp = other.Vtmp;
        }
        if (other.HasVp) {
          Vp = other.Vp;
        }
        if (other.HasVuse) {
          Vuse = other.Vuse;
        }
        if (other.HasVstatus) {
          Vstatus = other.Vstatus;
        }
        if (other.HasPosition) {
          Position = other.Position;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_cDBStatusModelFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _cDBStatusModelFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasV = input.ReadString(ref result.v_);
              break;
            }
            case 18: {
              result.hasVtmp = input.ReadString(ref result.vtmp_);
              break;
            }
            case 26: {
              result.hasVp = input.ReadString(ref result.vp_);
              break;
            }
            case 34: {
              result.hasVuse = input.ReadString(ref result.vuse_);
              break;
            }
            case 42: {
              result.hasVstatus = input.ReadString(ref result.vstatus_);
              break;
            }
            case 50: {
              result.hasPosition = input.ReadString(ref result.position_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasV {
        get { return result.hasV; }
      }
      public string V {
        get { return result.V; }
        set { SetV(value); }
      }
      public Builder SetV(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasV = true;
        result.v_ = value;
        return this;
      }
      public Builder ClearV() {
        PrepareBuilder();
        result.hasV = false;
        result.v_ = "";
        return this;
      }
      
      public bool HasVtmp {
        get { return result.hasVtmp; }
      }
      public string Vtmp {
        get { return result.Vtmp; }
        set { SetVtmp(value); }
      }
      public Builder SetVtmp(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasVtmp = true;
        result.vtmp_ = value;
        return this;
      }
      public Builder ClearVtmp() {
        PrepareBuilder();
        result.hasVtmp = false;
        result.vtmp_ = "";
        return this;
      }
      
      public bool HasVp {
        get { return result.hasVp; }
      }
      public string Vp {
        get { return result.Vp; }
        set { SetVp(value); }
      }
      public Builder SetVp(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasVp = true;
        result.vp_ = value;
        return this;
      }
      public Builder ClearVp() {
        PrepareBuilder();
        result.hasVp = false;
        result.vp_ = "";
        return this;
      }
      
      public bool HasVuse {
        get { return result.hasVuse; }
      }
      public string Vuse {
        get { return result.Vuse; }
        set { SetVuse(value); }
      }
      public Builder SetVuse(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasVuse = true;
        result.vuse_ = value;
        return this;
      }
      public Builder ClearVuse() {
        PrepareBuilder();
        result.hasVuse = false;
        result.vuse_ = "";
        return this;
      }
      
      public bool HasVstatus {
        get { return result.hasVstatus; }
      }
      public string Vstatus {
        get { return result.Vstatus; }
        set { SetVstatus(value); }
      }
      public Builder SetVstatus(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasVstatus = true;
        result.vstatus_ = value;
        return this;
      }
      public Builder ClearVstatus() {
        PrepareBuilder();
        result.hasVstatus = false;
        result.vstatus_ = "";
        return this;
      }
      
      public bool HasPosition {
        get { return result.hasPosition; }
      }
      public string Position {
        get { return result.Position; }
        set { SetPosition(value); }
      }
      public Builder SetPosition(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPosition = true;
        result.position_ = value;
        return this;
      }
      public Builder ClearPosition() {
        PrepareBuilder();
        result.hasPosition = false;
        result.position_ = "";
        return this;
      }
    }
    static CDBStatusModel() {
      object.ReferenceEquals(global::com.imlaidian.protobuf.model.CDBStatus.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
