// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.imlaidian.protobuf.model {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class LaidianStatus {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.LaidianStatusModel, global::com.imlaidian.protobuf.model.LaidianStatusModel.Builder> internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static LaidianStatus() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNMYWlkaWFuU3RhdHVzLnByb3RvEhxjb20uaW1sYWlkaWFuLnByb3RvYnVm", 
            "Lm1vZGVsGg9DREJTdGF0dXMucHJvdG8itgIKEkxhaWRpYW5TdGF0dXNNb2Rl", 
            "bBISCgR0eXBlGAIgASgJUgR0eXBlEhoKCHRlcm1pbmFsGAMgASgJUgh0ZXJt", 
            "aW5hbBISCgR0aW1lGAQgASgJUgR0aW1lEg4KAnZkGAUgASgJUgJ2ZBIQCgNz", 
            "bWsYBiABKAlSA3NtaxISCgR0ZW1wGAcgASgJUgR0ZW1wEhYKBnN0YXR1cxgI", 
            "IAEoCVIGc3RhdHVzEhQKBWhzbnVtGAkgASgJUgVoc251bRIgCgtsaW5lc3N0", 
            "YXR1cxgKIAEoCVILbGluZXNzdGF0dXMSFAoFbGluZXMYCyADKAVSBWxpbmVz", 
            "EkAKBGNkYnMYDCADKAsyLC5jb20uaW1sYWlkaWFuLnByb3RvYnVmLm1vZGVs", 
            "LkNEQlN0YXR1c01vZGVsUgRjZGJzQi0KHGNvbS5pbWxhaWRpYW4ucHJvdG9i", 
          "dWYubW9kZWxCDUxhaWRpYW5TdGF0dXNiBnByb3RvMw=="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.LaidianStatusModel, global::com.imlaidian.protobuf.model.LaidianStatusModel.Builder>(internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__Descriptor,
                new string[] { "Type", "Terminal", "Time", "Vd", "Smk", "Temp", "Status", "Hsnum", "Linesstatus", "Lines", "Cdbs", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        global::com.imlaidian.protobuf.model.CDBStatus.RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::com.imlaidian.protobuf.model.CDBStatus.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LaidianStatusModel : pb::GeneratedMessage<LaidianStatusModel, LaidianStatusModel.Builder> {
    private LaidianStatusModel() { }
    private static readonly LaidianStatusModel defaultInstance = new LaidianStatusModel().MakeReadOnly();
    private static readonly string[] _laidianStatusModelFieldNames = new string[] { "cdbs", "hsnum", "lines", "linesstatus", "smk", "status", "temp", "terminal", "time", "type", "vd" };
    private static readonly uint[] _laidianStatusModelFieldTags = new uint[] { 98, 74, 88, 82, 50, 66, 58, 26, 34, 18, 42 };
    public static LaidianStatusModel DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override LaidianStatusModel DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override LaidianStatusModel ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.imlaidian.protobuf.model.LaidianStatus.internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<LaidianStatusModel, LaidianStatusModel.Builder> InternalFieldAccessors {
      get { return global::com.imlaidian.protobuf.model.LaidianStatus.internal__static_com_imlaidian_protobuf_model_LaidianStatusModel__FieldAccessorTable; }
    }
    
    public const int TypeFieldNumber = 2;
    private bool hasType;
    private string type_ = "";
    public bool HasType {
      get { return hasType; }
    }
    public string Type {
      get { return type_; }
    }
    
    public const int TerminalFieldNumber = 3;
    private bool hasTerminal;
    private string terminal_ = "";
    public bool HasTerminal {
      get { return hasTerminal; }
    }
    public string Terminal {
      get { return terminal_; }
    }
    
    public const int TimeFieldNumber = 4;
    private bool hasTime;
    private string time_ = "";
    public bool HasTime {
      get { return hasTime; }
    }
    public string Time {
      get { return time_; }
    }
    
    public const int VdFieldNumber = 5;
    private bool hasVd;
    private string vd_ = "";
    public bool HasVd {
      get { return hasVd; }
    }
    public string Vd {
      get { return vd_; }
    }
    
    public const int SmkFieldNumber = 6;
    private bool hasSmk;
    private string smk_ = "";
    public bool HasSmk {
      get { return hasSmk; }
    }
    public string Smk {
      get { return smk_; }
    }
    
    public const int TempFieldNumber = 7;
    private bool hasTemp;
    private string temp_ = "";
    public bool HasTemp {
      get { return hasTemp; }
    }
    public string Temp {
      get { return temp_; }
    }
    
    public const int StatusFieldNumber = 8;
    private bool hasStatus;
    private string status_ = "";
    public bool HasStatus {
      get { return hasStatus; }
    }
    public string Status {
      get { return status_; }
    }
    
    public const int HsnumFieldNumber = 9;
    private bool hasHsnum;
    private string hsnum_ = "";
    public bool HasHsnum {
      get { return hasHsnum; }
    }
    public string Hsnum {
      get { return hsnum_; }
    }
    
    public const int LinesstatusFieldNumber = 10;
    private bool hasLinesstatus;
    private string linesstatus_ = "";
    public bool HasLinesstatus {
      get { return hasLinesstatus; }
    }
    public string Linesstatus {
      get { return linesstatus_; }
    }
    
    public const int LinesFieldNumber = 11;
    private pbc::PopsicleList<int> lines_ = new pbc::PopsicleList<int>();
    public scg::IList<int> LinesList {
      get { return pbc::Lists.AsReadOnly(lines_); }
    }
    public int LinesCount {
      get { return lines_.Count; }
    }
    public int GetLines(int index) {
      return lines_[index];
    }
    
    public const int CdbsFieldNumber = 12;
    private pbc::PopsicleList<global::com.imlaidian.protobuf.model.CDBStatusModel> cdbs_ = new pbc::PopsicleList<global::com.imlaidian.protobuf.model.CDBStatusModel>();
    public scg::IList<global::com.imlaidian.protobuf.model.CDBStatusModel> CdbsList {
      get { return cdbs_; }
    }
    public int CdbsCount {
      get { return cdbs_.Count; }
    }
    public global::com.imlaidian.protobuf.model.CDBStatusModel GetCdbs(int index) {
      return cdbs_[index];
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _laidianStatusModelFieldNames;
      if (hasType) {
        output.WriteString(2, field_names[9], Type);
      }
      if (hasTerminal) {
        output.WriteString(3, field_names[7], Terminal);
      }
      if (hasTime) {
        output.WriteString(4, field_names[8], Time);
      }
      if (hasVd) {
        output.WriteString(5, field_names[10], Vd);
      }
      if (hasSmk) {
        output.WriteString(6, field_names[4], Smk);
      }
      if (hasTemp) {
        output.WriteString(7, field_names[6], Temp);
      }
      if (hasStatus) {
        output.WriteString(8, field_names[5], Status);
      }
      if (hasHsnum) {
        output.WriteString(9, field_names[1], Hsnum);
      }
      if (hasLinesstatus) {
        output.WriteString(10, field_names[3], Linesstatus);
      }
      if (lines_.Count > 0) {
        output.WriteInt32Array(11, field_names[2], lines_);
      }
      if (cdbs_.Count > 0) {
        output.WriteMessageArray(12, field_names[0], cdbs_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasType) {
        size += pb::CodedOutputStream.ComputeStringSize(2, Type);
      }
      if (hasTerminal) {
        size += pb::CodedOutputStream.ComputeStringSize(3, Terminal);
      }
      if (hasTime) {
        size += pb::CodedOutputStream.ComputeStringSize(4, Time);
      }
      if (hasVd) {
        size += pb::CodedOutputStream.ComputeStringSize(5, Vd);
      }
      if (hasSmk) {
        size += pb::CodedOutputStream.ComputeStringSize(6, Smk);
      }
      if (hasTemp) {
        size += pb::CodedOutputStream.ComputeStringSize(7, Temp);
      }
      if (hasStatus) {
        size += pb::CodedOutputStream.ComputeStringSize(8, Status);
      }
      if (hasHsnum) {
        size += pb::CodedOutputStream.ComputeStringSize(9, Hsnum);
      }
      if (hasLinesstatus) {
        size += pb::CodedOutputStream.ComputeStringSize(10, Linesstatus);
      }
      {
        int dataSize = 0;
        foreach (int element in LinesList) {
          dataSize += pb::CodedOutputStream.ComputeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * lines_.Count;
      }
      foreach (global::com.imlaidian.protobuf.model.CDBStatusModel element in CdbsList) {
        size += pb::CodedOutputStream.ComputeMessageSize(12, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static LaidianStatusModel ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static LaidianStatusModel ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static LaidianStatusModel ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LaidianStatusModel ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private LaidianStatusModel MakeReadOnly() {
      lines_.MakeReadOnly();
      cdbs_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(LaidianStatusModel prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<LaidianStatusModel, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(LaidianStatusModel cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private LaidianStatusModel result;
      
      private LaidianStatusModel PrepareBuilder() {
        if (resultIsReadOnly) {
          LaidianStatusModel original = result;
          result = new LaidianStatusModel();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override LaidianStatusModel MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.imlaidian.protobuf.model.LaidianStatusModel.Descriptor; }
      }
      
      public override LaidianStatusModel DefaultInstanceForType {
        get { return global::com.imlaidian.protobuf.model.LaidianStatusModel.DefaultInstance; }
      }
      
      public override LaidianStatusModel BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is LaidianStatusModel) {
          return MergeFrom((LaidianStatusModel) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(LaidianStatusModel other) {
        if (other == global::com.imlaidian.protobuf.model.LaidianStatusModel.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasType) {
          Type = other.Type;
        }
        if (other.HasTerminal) {
          Terminal = other.Terminal;
        }
        if (other.HasTime) {
          Time = other.Time;
        }
        if (other.HasVd) {
          Vd = other.Vd;
        }
        if (other.HasSmk) {
          Smk = other.Smk;
        }
        if (other.HasTemp) {
          Temp = other.Temp;
        }
        if (other.HasStatus) {
          Status = other.Status;
        }
        if (other.HasHsnum) {
          Hsnum = other.Hsnum;
        }
        if (other.HasLinesstatus) {
          Linesstatus = other.Linesstatus;
        }
        if (other.lines_.Count != 0) {
          result.lines_.Add(other.lines_);
        }
        if (other.cdbs_.Count != 0) {
          result.cdbs_.Add(other.cdbs_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_laidianStatusModelFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _laidianStatusModelFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 18: {
              result.hasType = input.ReadString(ref result.type_);
              break;
            }
            case 26: {
              result.hasTerminal = input.ReadString(ref result.terminal_);
              break;
            }
            case 34: {
              result.hasTime = input.ReadString(ref result.time_);
              break;
            }
            case 42: {
              result.hasVd = input.ReadString(ref result.vd_);
              break;
            }
            case 50: {
              result.hasSmk = input.ReadString(ref result.smk_);
              break;
            }
            case 58: {
              result.hasTemp = input.ReadString(ref result.temp_);
              break;
            }
            case 66: {
              result.hasStatus = input.ReadString(ref result.status_);
              break;
            }
            case 74: {
              result.hasHsnum = input.ReadString(ref result.hsnum_);
              break;
            }
            case 82: {
              result.hasLinesstatus = input.ReadString(ref result.linesstatus_);
              break;
            }
            case 90:
            case 88: {
              input.ReadInt32Array(tag, field_name, result.lines_);
              break;
            }
            case 98: {
              input.ReadMessageArray(tag, field_name, result.cdbs_, global::com.imlaidian.protobuf.model.CDBStatusModel.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasType {
        get { return result.hasType; }
      }
      public string Type {
        get { return result.Type; }
        set { SetType(value); }
      }
      public Builder SetType(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder ClearType() {
        PrepareBuilder();
        result.hasType = false;
        result.type_ = "";
        return this;
      }
      
      public bool HasTerminal {
        get { return result.hasTerminal; }
      }
      public string Terminal {
        get { return result.Terminal; }
        set { SetTerminal(value); }
      }
      public Builder SetTerminal(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTerminal = true;
        result.terminal_ = value;
        return this;
      }
      public Builder ClearTerminal() {
        PrepareBuilder();
        result.hasTerminal = false;
        result.terminal_ = "";
        return this;
      }
      
      public bool HasTime {
        get { return result.hasTime; }
      }
      public string Time {
        get { return result.Time; }
        set { SetTime(value); }
      }
      public Builder SetTime(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTime = true;
        result.time_ = value;
        return this;
      }
      public Builder ClearTime() {
        PrepareBuilder();
        result.hasTime = false;
        result.time_ = "";
        return this;
      }
      
      public bool HasVd {
        get { return result.hasVd; }
      }
      public string Vd {
        get { return result.Vd; }
        set { SetVd(value); }
      }
      public Builder SetVd(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasVd = true;
        result.vd_ = value;
        return this;
      }
      public Builder ClearVd() {
        PrepareBuilder();
        result.hasVd = false;
        result.vd_ = "";
        return this;
      }
      
      public bool HasSmk {
        get { return result.hasSmk; }
      }
      public string Smk {
        get { return result.Smk; }
        set { SetSmk(value); }
      }
      public Builder SetSmk(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasSmk = true;
        result.smk_ = value;
        return this;
      }
      public Builder ClearSmk() {
        PrepareBuilder();
        result.hasSmk = false;
        result.smk_ = "";
        return this;
      }
      
      public bool HasTemp {
        get { return result.hasTemp; }
      }
      public string Temp {
        get { return result.Temp; }
        set { SetTemp(value); }
      }
      public Builder SetTemp(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTemp = true;
        result.temp_ = value;
        return this;
      }
      public Builder ClearTemp() {
        PrepareBuilder();
        result.hasTemp = false;
        result.temp_ = "";
        return this;
      }
      
      public bool HasStatus {
        get { return result.hasStatus; }
      }
      public string Status {
        get { return result.Status; }
        set { SetStatus(value); }
      }
      public Builder SetStatus(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder ClearStatus() {
        PrepareBuilder();
        result.hasStatus = false;
        result.status_ = "";
        return this;
      }
      
      public bool HasHsnum {
        get { return result.hasHsnum; }
      }
      public string Hsnum {
        get { return result.Hsnum; }
        set { SetHsnum(value); }
      }
      public Builder SetHsnum(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasHsnum = true;
        result.hsnum_ = value;
        return this;
      }
      public Builder ClearHsnum() {
        PrepareBuilder();
        result.hasHsnum = false;
        result.hsnum_ = "";
        return this;
      }
      
      public bool HasLinesstatus {
        get { return result.hasLinesstatus; }
      }
      public string Linesstatus {
        get { return result.Linesstatus; }
        set { SetLinesstatus(value); }
      }
      public Builder SetLinesstatus(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasLinesstatus = true;
        result.linesstatus_ = value;
        return this;
      }
      public Builder ClearLinesstatus() {
        PrepareBuilder();
        result.hasLinesstatus = false;
        result.linesstatus_ = "";
        return this;
      }
      
      public pbc::IPopsicleList<int> LinesList {
        get { return PrepareBuilder().lines_; }
      }
      public int LinesCount {
        get { return result.LinesCount; }
      }
      public int GetLines(int index) {
        return result.GetLines(index);
      }
      public Builder SetLines(int index, int value) {
        PrepareBuilder();
        result.lines_[index] = value;
        return this;
      }
      public Builder AddLines(int value) {
        PrepareBuilder();
        result.lines_.Add(value);
        return this;
      }
      public Builder AddRangeLines(scg::IEnumerable<int> values) {
        PrepareBuilder();
        result.lines_.Add(values);
        return this;
      }
      public Builder ClearLines() {
        PrepareBuilder();
        result.lines_.Clear();
        return this;
      }
      
      public pbc::IPopsicleList<global::com.imlaidian.protobuf.model.CDBStatusModel> CdbsList {
        get { return PrepareBuilder().cdbs_; }
      }
      public int CdbsCount {
        get { return result.CdbsCount; }
      }
      public global::com.imlaidian.protobuf.model.CDBStatusModel GetCdbs(int index) {
        return result.GetCdbs(index);
      }
      public Builder SetCdbs(int index, global::com.imlaidian.protobuf.model.CDBStatusModel value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.cdbs_[index] = value;
        return this;
      }
      public Builder SetCdbs(int index, global::com.imlaidian.protobuf.model.CDBStatusModel.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.cdbs_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddCdbs(global::com.imlaidian.protobuf.model.CDBStatusModel value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.cdbs_.Add(value);
        return this;
      }
      public Builder AddCdbs(global::com.imlaidian.protobuf.model.CDBStatusModel.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.cdbs_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeCdbs(scg::IEnumerable<global::com.imlaidian.protobuf.model.CDBStatusModel> values) {
        PrepareBuilder();
        result.cdbs_.Add(values);
        return this;
      }
      public Builder ClearCdbs() {
        PrepareBuilder();
        result.cdbs_.Clear();
        return this;
      }
    }
    static LaidianStatusModel() {
      object.ReferenceEquals(global::com.imlaidian.protobuf.model.LaidianStatus.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
