// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.imlaidian.protobuf.model {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class LaidianTask {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.LaidianTaskModel, global::com.imlaidian.protobuf.model.LaidianTaskModel.Builder> internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static LaidianTask() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMYWlkaWFuVGFzay5wcm90bxIcY29tLmltbGFpZGlhbi5wcm90b2J1Zi5t", 
            "b2RlbCLaAQoQTGFpZGlhblRhc2tNb2RlbBISCgR0eXBlGAEgASgJUgR0eXBl", 
            "EhYKBnRhc2tJZBgCIAEoCVIGdGFza0lkEhoKCGxpbmVUeXBlGAMgASgJUghs", 
            "aW5lVHlwZRIUCgVjZGJJRBgEIAEoCVIFY2RiSUQSIgoMdXNlck5pY2tOYW1l", 
            "GAUgASgJUgx1c2VyTmlja05hbWUSIAoLdXNlckhlYWRQaWMYBiABKAlSC3Vz", 
            "ZXJIZWFkUGljEiIKDHJlc3VsdFN0YXR1cxgHIAEoCVIMcmVzdWx0U3RhdHVz", 
            "QjEKImNvbS5pbWxhaWRpYW4ubmV0dHkucHJvdG9idWYubW9kZWxCC0xhaWRp", 
          "YW5UYXNrYgZwcm90bzM="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.LaidianTaskModel, global::com.imlaidian.protobuf.model.LaidianTaskModel.Builder>(internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__Descriptor,
                new string[] { "Type", "TaskId", "LineType", "CdbID", "UserNickName", "UserHeadPic", "ResultStatus", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LaidianTaskModel : pb::GeneratedMessage<LaidianTaskModel, LaidianTaskModel.Builder> {
    private LaidianTaskModel() { }
    private static readonly LaidianTaskModel defaultInstance = new LaidianTaskModel().MakeReadOnly();
    private static readonly string[] _laidianTaskModelFieldNames = new string[] { "cdbID", "lineType", "resultStatus", "taskId", "type", "userHeadPic", "userNickName" };
    private static readonly uint[] _laidianTaskModelFieldTags = new uint[] { 34, 26, 58, 18, 10, 50, 42 };
    public static LaidianTaskModel DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override LaidianTaskModel DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override LaidianTaskModel ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.imlaidian.protobuf.model.LaidianTask.internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<LaidianTaskModel, LaidianTaskModel.Builder> InternalFieldAccessors {
      get { return global::com.imlaidian.protobuf.model.LaidianTask.internal__static_com_imlaidian_protobuf_model_LaidianTaskModel__FieldAccessorTable; }
    }
    
    public const int TypeFieldNumber = 1;
    private bool hasType;
    private string type_ = "";
    public bool HasType {
      get { return hasType; }
    }
    public string Type {
      get { return type_; }
    }
    
    public const int TaskIdFieldNumber = 2;
    private bool hasTaskId;
    private string taskId_ = "";
    public bool HasTaskId {
      get { return hasTaskId; }
    }
    public string TaskId {
      get { return taskId_; }
    }
    
    public const int LineTypeFieldNumber = 3;
    private bool hasLineType;
    private string lineType_ = "";
    public bool HasLineType {
      get { return hasLineType; }
    }
    public string LineType {
      get { return lineType_; }
    }
    
    public const int CdbIDFieldNumber = 4;
    private bool hasCdbID;
    private string cdbID_ = "";
    public bool HasCdbID {
      get { return hasCdbID; }
    }
    public string CdbID {
      get { return cdbID_; }
    }
    
    public const int UserNickNameFieldNumber = 5;
    private bool hasUserNickName;
    private string userNickName_ = "";
    public bool HasUserNickName {
      get { return hasUserNickName; }
    }
    public string UserNickName {
      get { return userNickName_; }
    }
    
    public const int UserHeadPicFieldNumber = 6;
    private bool hasUserHeadPic;
    private string userHeadPic_ = "";
    public bool HasUserHeadPic {
      get { return hasUserHeadPic; }
    }
    public string UserHeadPic {
      get { return userHeadPic_; }
    }
    
    public const int ResultStatusFieldNumber = 7;
    private bool hasResultStatus;
    private string resultStatus_ = "";
    public bool HasResultStatus {
      get { return hasResultStatus; }
    }
    public string ResultStatus {
      get { return resultStatus_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _laidianTaskModelFieldNames;
      if (hasType) {
        output.WriteString(1, field_names[4], Type);
      }
      if (hasTaskId) {
        output.WriteString(2, field_names[3], TaskId);
      }
      if (hasLineType) {
        output.WriteString(3, field_names[1], LineType);
      }
      if (hasCdbID) {
        output.WriteString(4, field_names[0], CdbID);
      }
      if (hasUserNickName) {
        output.WriteString(5, field_names[6], UserNickName);
      }
      if (hasUserHeadPic) {
        output.WriteString(6, field_names[5], UserHeadPic);
      }
      if (hasResultStatus) {
        output.WriteString(7, field_names[2], ResultStatus);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasType) {
        size += pb::CodedOutputStream.ComputeStringSize(1, Type);
      }
      if (hasTaskId) {
        size += pb::CodedOutputStream.ComputeStringSize(2, TaskId);
      }
      if (hasLineType) {
        size += pb::CodedOutputStream.ComputeStringSize(3, LineType);
      }
      if (hasCdbID) {
        size += pb::CodedOutputStream.ComputeStringSize(4, CdbID);
      }
      if (hasUserNickName) {
        size += pb::CodedOutputStream.ComputeStringSize(5, UserNickName);
      }
      if (hasUserHeadPic) {
        size += pb::CodedOutputStream.ComputeStringSize(6, UserHeadPic);
      }
      if (hasResultStatus) {
        size += pb::CodedOutputStream.ComputeStringSize(7, ResultStatus);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static LaidianTaskModel ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static LaidianTaskModel ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static LaidianTaskModel ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LaidianTaskModel ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private LaidianTaskModel MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(LaidianTaskModel prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<LaidianTaskModel, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(LaidianTaskModel cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private LaidianTaskModel result;
      
      private LaidianTaskModel PrepareBuilder() {
        if (resultIsReadOnly) {
          LaidianTaskModel original = result;
          result = new LaidianTaskModel();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override LaidianTaskModel MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.imlaidian.protobuf.model.LaidianTaskModel.Descriptor; }
      }
      
      public override LaidianTaskModel DefaultInstanceForType {
        get { return global::com.imlaidian.protobuf.model.LaidianTaskModel.DefaultInstance; }
      }
      
      public override LaidianTaskModel BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is LaidianTaskModel) {
          return MergeFrom((LaidianTaskModel) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(LaidianTaskModel other) {
        if (other == global::com.imlaidian.protobuf.model.LaidianTaskModel.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasType) {
          Type = other.Type;
        }
        if (other.HasTaskId) {
          TaskId = other.TaskId;
        }
        if (other.HasLineType) {
          LineType = other.LineType;
        }
        if (other.HasCdbID) {
          CdbID = other.CdbID;
        }
        if (other.HasUserNickName) {
          UserNickName = other.UserNickName;
        }
        if (other.HasUserHeadPic) {
          UserHeadPic = other.UserHeadPic;
        }
        if (other.HasResultStatus) {
          ResultStatus = other.ResultStatus;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_laidianTaskModelFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _laidianTaskModelFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasType = input.ReadString(ref result.type_);
              break;
            }
            case 18: {
              result.hasTaskId = input.ReadString(ref result.taskId_);
              break;
            }
            case 26: {
              result.hasLineType = input.ReadString(ref result.lineType_);
              break;
            }
            case 34: {
              result.hasCdbID = input.ReadString(ref result.cdbID_);
              break;
            }
            case 42: {
              result.hasUserNickName = input.ReadString(ref result.userNickName_);
              break;
            }
            case 50: {
              result.hasUserHeadPic = input.ReadString(ref result.userHeadPic_);
              break;
            }
            case 58: {
              result.hasResultStatus = input.ReadString(ref result.resultStatus_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasType {
        get { return result.hasType; }
      }
      public string Type {
        get { return result.Type; }
        set { SetType(value); }
      }
      public Builder SetType(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder ClearType() {
        PrepareBuilder();
        result.hasType = false;
        result.type_ = "";
        return this;
      }
      
      public bool HasTaskId {
        get { return result.hasTaskId; }
      }
      public string TaskId {
        get { return result.TaskId; }
        set { SetTaskId(value); }
      }
      public Builder SetTaskId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTaskId = true;
        result.taskId_ = value;
        return this;
      }
      public Builder ClearTaskId() {
        PrepareBuilder();
        result.hasTaskId = false;
        result.taskId_ = "";
        return this;
      }
      
      public bool HasLineType {
        get { return result.hasLineType; }
      }
      public string LineType {
        get { return result.LineType; }
        set { SetLineType(value); }
      }
      public Builder SetLineType(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasLineType = true;
        result.lineType_ = value;
        return this;
      }
      public Builder ClearLineType() {
        PrepareBuilder();
        result.hasLineType = false;
        result.lineType_ = "";
        return this;
      }
      
      public bool HasCdbID {
        get { return result.hasCdbID; }
      }
      public string CdbID {
        get { return result.CdbID; }
        set { SetCdbID(value); }
      }
      public Builder SetCdbID(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasCdbID = true;
        result.cdbID_ = value;
        return this;
      }
      public Builder ClearCdbID() {
        PrepareBuilder();
        result.hasCdbID = false;
        result.cdbID_ = "";
        return this;
      }
      
      public bool HasUserNickName {
        get { return result.hasUserNickName; }
      }
      public string UserNickName {
        get { return result.UserNickName; }
        set { SetUserNickName(value); }
      }
      public Builder SetUserNickName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasUserNickName = true;
        result.userNickName_ = value;
        return this;
      }
      public Builder ClearUserNickName() {
        PrepareBuilder();
        result.hasUserNickName = false;
        result.userNickName_ = "";
        return this;
      }
      
      public bool HasUserHeadPic {
        get { return result.hasUserHeadPic; }
      }
      public string UserHeadPic {
        get { return result.UserHeadPic; }
        set { SetUserHeadPic(value); }
      }
      public Builder SetUserHeadPic(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasUserHeadPic = true;
        result.userHeadPic_ = value;
        return this;
      }
      public Builder ClearUserHeadPic() {
        PrepareBuilder();
        result.hasUserHeadPic = false;
        result.userHeadPic_ = "";
        return this;
      }
      
      public bool HasResultStatus {
        get { return result.hasResultStatus; }
      }
      public string ResultStatus {
        get { return result.ResultStatus; }
        set { SetResultStatus(value); }
      }
      public Builder SetResultStatus(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasResultStatus = true;
        result.resultStatus_ = value;
        return this;
      }
      public Builder ClearResultStatus() {
        PrepareBuilder();
        result.hasResultStatus = false;
        result.resultStatus_ = "";
        return this;
      }
    }
    static LaidianTaskModel() {
      object.ReferenceEquals(global::com.imlaidian.protobuf.model.LaidianTask.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
