// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.imlaidian.protobuf.model {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class LaidianCommand {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.LaidianCommandModel, global::com.imlaidian.protobuf.model.LaidianCommandModel.Builder> internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static LaidianCommand() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRMYWlkaWFuQ29tbWFuZC5wcm90bxIcY29tLmltbGFpZGlhbi5wcm90b2J1", 
            "Zi5tb2RlbBoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byLoAQoTTGFpZGlh", 
            "bkNvbW1hbmRNb2RlbBJLCgttZXNzYWdlVHlwZRgBIAEoDjIpLmNvbS5pbWxh", 
            "aWRpYW4ucHJvdG9idWYubW9kZWwuTWVzc2FnZVR5cGVSC21lc3NhZ2VUeXBl", 
            "EjYKC2xhaWRpYW5EYXRhGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueVIL", 
            "bGFpZGlhbkRhdGESFgoGcmVzdWx0GAMgASgFUgZyZXN1bHQSGAoHbWVzc2Fn", 
            "ZRgEIAEoCVIHbWVzc2FnZRIaCgh0ZXJtaW5hbBgFIAEoCVIIdGVybWluYWwq", 
            "wAIKC01lc3NhZ2VUeXBlEg0KCUxPR0lOX1JFURAAEg4KCkxPR0lOX1JFU1AQ", 
            "ARINCglIRUFSVEJFQVQQAhIWChJMQUlESUFOX1NUQVRVU19SRVEQAxIXChNM", 
            "QUlESUFOX1NUQVRVU19SRVNQEAQSFgoSTEFJRElBTl9CT1JST1dfUkVREAUS", 
            "FwoTTEFJRElBTl9CT1JST1dfUkVTUBAGEhsKF0xBSURJQU5fQk9SUk9XX1JF", 
            "U1BfUkVWEAsSGAoUTEFJRElBTl9HSVZFQkFDS19SRVEQBxIZChVMQUlESUFO", 
            "X0dJVkVCQUNLX1JFU1AQCBIXChNMQUlESUFOX0JVWUxJTkVfUkVREAkSGAoU", 
            "TEFJRElBTl9CVVlMSU5FX1JFU1AQChIcChhMQUlESUFOX0JVWUxJTkVfUkVT", 
            "UF9SRVYQDEI0CiJjb20uaW1sYWlkaWFuLm5ldHR5LnByb3RvYnVmLm1vZGVs", 
          "Qg5MYWlkaWFuQ29tbWFuZGIGcHJvdG8z"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__Descriptor = Descriptor.MessageTypes[0];
        internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::com.imlaidian.protobuf.model.LaidianCommandModel, global::com.imlaidian.protobuf.model.LaidianCommandModel.Builder>(internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__Descriptor,
                new string[] { "MessageType", "LaidianData", "Result", "Message", "Terminal", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        global::google.protobuf.Proto.Any.RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::google.protobuf.Proto.Any.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum MessageType {
    LOGIN_REQ = 0,
    LOGIN_RESP = 1,
    HEARTBEAT = 2,
    LAIDIAN_STATUS_REQ = 3,
    LAIDIAN_STATUS_RESP = 4,
    LAIDIAN_BORROW_REQ = 5,
    LAIDIAN_BORROW_RESP = 6,
    LAIDIAN_BORROW_RESP_REV = 11,
    LAIDIAN_GIVEBACK_REQ = 7,
    LAIDIAN_GIVEBACK_RESP = 8,
    LAIDIAN_BUYLINE_REQ = 9,
    LAIDIAN_BUYLINE_RESP = 10,
    LAIDIAN_BUYLINE_RESP_REV = 12,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LaidianCommandModel : pb::GeneratedMessage<LaidianCommandModel, LaidianCommandModel.Builder> {
    private LaidianCommandModel() { }
    private static readonly LaidianCommandModel defaultInstance = new LaidianCommandModel().MakeReadOnly();
    private static readonly string[] _laidianCommandModelFieldNames = new string[] { "laidianData", "message", "messageType", "result", "terminal" };
    private static readonly uint[] _laidianCommandModelFieldTags = new uint[] { 18, 34, 8, 24, 42 };
    public static LaidianCommandModel DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override LaidianCommandModel DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override LaidianCommandModel ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::com.imlaidian.protobuf.model.LaidianCommand.internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<LaidianCommandModel, LaidianCommandModel.Builder> InternalFieldAccessors {
      get { return global::com.imlaidian.protobuf.model.LaidianCommand.internal__static_com_imlaidian_protobuf_model_LaidianCommandModel__FieldAccessorTable; }
    }
    
    public const int MessageTypeFieldNumber = 1;
    private bool hasMessageType;
    private global::com.imlaidian.protobuf.model.MessageType messageType_ = global::com.imlaidian.protobuf.model.MessageType.LOGIN_REQ;
    public bool HasMessageType {
      get { return hasMessageType; }
    }
    public global::com.imlaidian.protobuf.model.MessageType MessageType {
      get { return messageType_; }
    }
    
    public const int LaidianDataFieldNumber = 2;
    private bool hasLaidianData;
    private global::google.protobuf.Any laidianData_;
    public bool HasLaidianData {
      get { return hasLaidianData; }
    }
    public global::google.protobuf.Any LaidianData {
      get { return laidianData_ ?? global::google.protobuf.Any.DefaultInstance; }
    }
    
    public const int ResultFieldNumber = 3;
    private bool hasResult;
    private int result_;
    public bool HasResult {
      get { return hasResult; }
    }
    public int Result {
      get { return result_; }
    }
    
    public const int MessageFieldNumber = 4;
    private bool hasMessage;
    private string message_ = "";
    public bool HasMessage {
      get { return hasMessage; }
    }
    public string Message {
      get { return message_; }
    }
    
    public const int TerminalFieldNumber = 5;
    private bool hasTerminal;
    private string terminal_ = "";
    public bool HasTerminal {
      get { return hasTerminal; }
    }
    public string Terminal {
      get { return terminal_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _laidianCommandModelFieldNames;
      if (hasMessageType) {
        output.WriteEnum(1, field_names[2], (int) MessageType, MessageType);
      }
      if (hasLaidianData) {
        output.WriteMessage(2, field_names[0], LaidianData);
      }
      if (hasResult) {
        output.WriteInt32(3, field_names[3], Result);
      }
      if (hasMessage) {
        output.WriteString(4, field_names[1], Message);
      }
      if (hasTerminal) {
        output.WriteString(5, field_names[4], Terminal);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasMessageType) {
        size += pb::CodedOutputStream.ComputeEnumSize(1, (int) MessageType);
      }
      if (hasLaidianData) {
        size += pb::CodedOutputStream.ComputeMessageSize(2, LaidianData);
      }
      if (hasResult) {
        size += pb::CodedOutputStream.ComputeInt32Size(3, Result);
      }
      if (hasMessage) {
        size += pb::CodedOutputStream.ComputeStringSize(4, Message);
      }
      if (hasTerminal) {
        size += pb::CodedOutputStream.ComputeStringSize(5, Terminal);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static LaidianCommandModel ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static LaidianCommandModel ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static LaidianCommandModel ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static LaidianCommandModel ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private LaidianCommandModel MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(LaidianCommandModel prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<LaidianCommandModel, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(LaidianCommandModel cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private LaidianCommandModel result;
      
      private LaidianCommandModel PrepareBuilder() {
        if (resultIsReadOnly) {
          LaidianCommandModel original = result;
          result = new LaidianCommandModel();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override LaidianCommandModel MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::com.imlaidian.protobuf.model.LaidianCommandModel.Descriptor; }
      }
      
      public override LaidianCommandModel DefaultInstanceForType {
        get { return global::com.imlaidian.protobuf.model.LaidianCommandModel.DefaultInstance; }
      }
      
      public override LaidianCommandModel BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is LaidianCommandModel) {
          return MergeFrom((LaidianCommandModel) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(LaidianCommandModel other) {
        if (other == global::com.imlaidian.protobuf.model.LaidianCommandModel.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasMessageType) {
          MessageType = other.MessageType;
        }
        if (other.HasLaidianData) {
          MergeLaidianData(other.LaidianData);
        }
        if (other.HasResult) {
          Result = other.Result;
        }
        if (other.HasMessage) {
          Message = other.Message;
        }
        if (other.HasTerminal) {
          Terminal = other.Terminal;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_laidianCommandModelFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _laidianCommandModelFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.messageType_, out unknown)) {
                result.hasMessageType = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 18: {
              global::google.protobuf.Any.Builder subBuilder = global::google.protobuf.Any.CreateBuilder();
              if (result.hasLaidianData) {
                subBuilder.MergeFrom(LaidianData);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              LaidianData = subBuilder.BuildPartial();
              break;
            }
            case 24: {
              result.hasResult = input.ReadInt32(ref result.result_);
              break;
            }
            case 34: {
              result.hasMessage = input.ReadString(ref result.message_);
              break;
            }
            case 42: {
              result.hasTerminal = input.ReadString(ref result.terminal_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasMessageType {
       get { return result.hasMessageType; }
      }
      public global::com.imlaidian.protobuf.model.MessageType MessageType {
        get { return result.MessageType; }
        set { SetMessageType(value); }
      }
      public Builder SetMessageType(global::com.imlaidian.protobuf.model.MessageType value) {
        PrepareBuilder();
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder ClearMessageType() {
        PrepareBuilder();
        result.hasMessageType = false;
        result.messageType_ = global::com.imlaidian.protobuf.model.MessageType.LOGIN_REQ;
        return this;
      }
      
      public bool HasLaidianData {
       get { return result.hasLaidianData; }
      }
      public global::google.protobuf.Any LaidianData {
        get { return result.LaidianData; }
        set { SetLaidianData(value); }
      }
      public Builder SetLaidianData(global::google.protobuf.Any value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasLaidianData = true;
        result.laidianData_ = value;
        return this;
      }
      public Builder SetLaidianData(global::google.protobuf.Any.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.hasLaidianData = true;
        result.laidianData_ = builderForValue.Build();
        return this;
      }
      public Builder MergeLaidianData(global::google.protobuf.Any value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        if (result.hasLaidianData &&
            result.laidianData_ != global::google.protobuf.Any.DefaultInstance) {
            result.laidianData_ = global::google.protobuf.Any.CreateBuilder(result.laidianData_).MergeFrom(value).BuildPartial();
        } else {
          result.laidianData_ = value;
        }
        result.hasLaidianData = true;
        return this;
      }
      public Builder ClearLaidianData() {
        PrepareBuilder();
        result.hasLaidianData = false;
        result.laidianData_ = null;
        return this;
      }
      
      public bool HasResult {
        get { return result.hasResult; }
      }
      public int Result {
        get { return result.Result; }
        set { SetResult(value); }
      }
      public Builder SetResult(int value) {
        PrepareBuilder();
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder ClearResult() {
        PrepareBuilder();
        result.hasResult = false;
        result.result_ = 0;
        return this;
      }
      
      public bool HasMessage {
        get { return result.hasMessage; }
      }
      public string Message {
        get { return result.Message; }
        set { SetMessage(value); }
      }
      public Builder SetMessage(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder ClearMessage() {
        PrepareBuilder();
        result.hasMessage = false;
        result.message_ = "";
        return this;
      }
      
      public bool HasTerminal {
        get { return result.hasTerminal; }
      }
      public string Terminal {
        get { return result.Terminal; }
        set { SetTerminal(value); }
      }
      public Builder SetTerminal(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTerminal = true;
        result.terminal_ = value;
        return this;
      }
      public Builder ClearTerminal() {
        PrepareBuilder();
        result.hasTerminal = false;
        result.terminal_ = "";
        return this;
      }
    }
    static LaidianCommandModel() {
      object.ReferenceEquals(global::com.imlaidian.protobuf.model.LaidianCommand.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
